In [1]:
import numpy as np

In [3]:
#1.Tạo array arr có kích thước 3x3 với các giá trị True
arr = np.full(3, 3), True
print("arr (3x3 với giá trị True): \n", arr)

arr (3x3 với giá trị True): 
 (array([3, 3, 3]), True)


In [4]:
#2.Tạo array 1 chiều arr_1D và chuyển đổi sang arr_2D, đổi cột 1 và cột 3
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
arr_2D[:, [1, 2]] = arr_2D[:, [2, 1]]  # Chuyển cột 1 sang cột 3 và ngược lại
print("arr_2D sau khi đổi cột 1 và cột 3:\n", arr_2D)

arr_2D sau khi đổi cột 1 và cột 3:
 [[0 2 1]
 [3 5 4]
 [6 8 7]]


In [5]:
#3. Chuyển dòng 1 sang dòng 2 và ngược lại
arr_2D[[0, 1]] = arr_2D[[1, 0]]  # Đổi dòng 1 và dòng 2
print("arr_2D sau khi đổi dòng 1 và dòng 2:\n", arr_2D)


arr_2D sau khi đổi dòng 1 và dòng 2:
 [[3 5 4]
 [0 2 1]
 [6 8 7]]


In [6]:
#4. Đảo ngược các dòng của arr_2D
arr_2D = arr_2D[::-1]
print("arr_2D sau khi đảo ngược các dòng:\n", arr_2D)

arr_2D sau khi đảo ngược các dòng:
 [[6 8 7]
 [0 2 1]
 [3 5 4]]


In [7]:
#5. Đảo ngược các cột của arr_2D
arr_2D = arr_2D[:, ::-1]
print("arr_2D sau khi đảo ngược các cột:\n", arr_2D)

arr_2D sau khi đảo ngược các cột:
 [[7 8 6]
 [1 2 0]
 [4 5 3]]


In [8]:
#6. Kiểm tra trong arr_2D_null có giá trị rỗng hay không
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()
print("Có giá trị rỗng (NaN) trong arr_2D_null:", has_nan)

Có giá trị rỗng (NaN) trong arr_2D_null: True


In [9]:
#7. Thay thế giá trị null bằng 0
arr_2D_null = np.nan_to_num(arr_2D_null, nan=0)
print("arr_2D_null sau khi thay thế giá trị NaN bằng 0:\n", arr_2D_null)

arr_2D_null sau khi thay thế giá trị NaN bằng 0:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
